### ISSUE TITLE
Mistake in documentation

### ISSUE THREAD

**Issue by trocho** [ijpatricio/mingle#28]
Hello, 

There is a mistake at https://minglejs.unitedbycode.com/manual-instructions

The directive `@viteReactRefresh` should be before `@stack('scripts')` otherwise, it cause an error like this the following one

```
Uncaught Error: @vitejs/plugin-react can't detect preamble. Something is wrong.
```
![Screenshot 2024-11-02 at 15 51 57](https://github.com/user-attachments/assets/3767192b-2622-420f-b738-e57904b28e2e)

Now is:
```
 (...)
        <!-- Fonts -->
        <link rel="preconnect" href="https://fonts.bunny.net">
        <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />

        <!-- Scripts -->
        @stack('scripts')
        <!-- If you're using React -->
        @viteReactRefresh
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body class="font-sans text-gray-900 antialiased">
        
    (...)
```

**Comment by ijpatricio** [comment]
Hey @trocho !

Thank you so much! I totally forgot to update docs after hitting myself with that scenario!

How are. you enjoying Mingle, apart from that??

Thanks!!
